# Generates the C++ source that carries the overlay's language CSVs and UI
# font as byte arrays, so AwowLabOverlay.exe runs as one self-contained
# file with no data folder. Declarations live in the checked-in header
# Core/Overlay/EmbeddedOverlayAssets.h; this script writes the matching
# definitions from whatever is on disk at build time.
#
# Script mode usage (wired up as an add_custom_command):
#   cmake -DDATA_DIR=<...>/AwowLab/data -DOUTPUT_CPP=<path> -P embed_overlay_assets.cmake
#
# The same script serves the private repo and the published overlay repo.
# Inputs:
#   ${DATA_DIR}/lang/*.csv                 one array per locale
#   ${DATA_DIR}/fonts/NotoSans-Regular.ttf the UI font (license: OFL.txt)

cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED DATA_DIR OR NOT DEFINED OUTPUT_CPP)
    message(FATAL_ERROR "embed_overlay_assets.cmake needs -DDATA_DIR=... and -DOUTPUT_CPP=...")
endif()

# CMake regex has no bounded repetition, so build the 32-bytes-per-line
# pattern by hand. 32 bytes per output line keeps the generated file well
# under compiler line-length limits.
set(_byte "[0-9a-f][0-9a-f]")
set(_line_pattern "")
foreach(_i RANGE 31)
    string(APPEND _line_pattern "${_byte}")
endforeach()

# Read one file and format its contents as C array initializer lines.
function(file_to_byte_lines path out_var)
    file(READ "${path}" hex HEX)
    if(hex STREQUAL "")
        message(FATAL_ERROR "refusing to embed empty file: ${path}")
    endif()
    string(REGEX REPLACE "(${_line_pattern})" "\\1\n" hex "${hex}")
    string(REGEX REPLACE "(${_byte})" "0x\\1," hex "${hex}")
    set(${out_var} "${hex}" PARENT_SCOPE)
endfunction()

file(GLOB lang_csvs "${DATA_DIR}/lang/*.csv")
list(SORT lang_csvs)
if(NOT lang_csvs)
    message(FATAL_ERROR "no language CSVs found under ${DATA_DIR}/lang")
endif()

set(arrays "")
set(table "")
foreach(csv IN LISTS lang_csvs)
    get_filename_component(code "${csv}" NAME_WE)
    file_to_byte_lines("${csv}" bytes)
    string(APPEND arrays "const unsigned char kCsv_${code}[] = {\n${bytes}\n};\n\n")
    string(APPEND table "    {\"${code}\", kCsv_${code}, sizeof(kCsv_${code})},\n")
endforeach()

set(font_path "${DATA_DIR}/fonts/NotoSans-Regular.ttf")
if(NOT EXISTS "${font_path}")
    message(FATAL_ERROR "UI font not found at ${font_path}")
endif()
file_to_byte_lines("${font_path}" font_bytes)

file(WRITE "${OUTPUT_CPP}" "\
// Generated by cmake/embed_overlay_assets.cmake - do not edit.
#include \"Core/Overlay/EmbeddedOverlayAssets.h\"

namespace awow::embedded {
namespace {

${arrays}const unsigned char kFontBytes[] = {
${font_bytes}
};

} // anonymous namespace

const LocaleCsv kLocaleCsvs[] = {
${table}};
const size_t kLocaleCsvCount = sizeof(kLocaleCsvs) / sizeof(kLocaleCsvs[0]);

const unsigned char* const kUiFont = kFontBytes;
const size_t kUiFontSize = sizeof(kFontBytes);

} // namespace awow::embedded
")

message(STATUS "embedded ${DATA_DIR} assets into ${OUTPUT_CPP}")
